// Native Electron integration checks. Uses an isolated data directory, never the user's progress.
import {app,BrowserWindow} from 'electron';
import {mkdtemp,writeFile,readFile,mkdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import assert from 'node:assert/strict';
const testData=await mkdtemp(join(tmpdir(),'fieldwork-desktop-test-'));
app.setPath('userData',testData);
await import('../dist-electron/main.js');
void app.whenReady().then(async()=>{
const sleep=n=>new Promise(r=>setTimeout(r,n));
const until=async(fn,message)=>{for(let i=0;i<160;i++){if(await fn())return;await sleep(100);}throw new Error(message);};
try{
 await until(()=>BrowserWindow.getAllWindows().length>0,'No desktop window');
 const win=BrowserWindow.getAllWindows()[0];
 const js=code=>win.webContents.executeJavaScript(code);
 const text=()=>js('document.body.innerText');
 const click=selector=>js(`document.querySelector(${JSON.stringify(selector)}).click()`);
 const errors=[];win.webContents.on('console-message',details=>{if(details.level==='error')errors.push(details.message);});
 await until(async()=>(await text()).includes('Make room for one good problem.'),'Dashboard did not load');
 assert.match(await text(),/10|Today/);
 await mkdir('artifacts',{recursive:true});
 await js('new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)))');
 await writeFile('artifacts/dashboard.png',(await win.webContents.capturePage()).toPNG());
 console.log('PASS: native dashboard and renderer bridge');
 await click('[data-action="start"]');
 await until(async()=>(await text()).includes('C++ workspace'),'Session did not open');
 await until(()=>js('!!document.querySelector(".monaco-editor")'),'Editor failed to mount');
 await until(async()=>(await text()).includes('--NORMAL--'),'Vim did not initialize in Normal mode');
 await js('document.querySelector(".monaco-editor textarea").focus()');
 const keypress=async key=>{win.webContents.sendInputEvent({type:'keyDown',keyCode:key});win.webContents.sendInputEvent({type:'keyUp',keyCode:key});await sleep(60);};
 await keypress('i');
 await until(async()=>(await text()).includes('--INSERT--'),'Vim did not enter Insert mode');
 await win.webContents.insertText('// vim-test\n');
 await until(async()=>JSON.parse(await js('window.fieldwork.load()')).active.code.includes('// vim-test'),'Insert-mode typing did not reach the model');
 await keypress('Escape');
 await until(async()=>(await text()).includes('--NORMAL--'),'Escape did not return to Normal mode');
 await keypress('g');await keypress('g');await keypress('d');await keypress('d');
 await until(async()=>!JSON.parse(await js('window.fieldwork.load()')).active.code.includes('// vim-test'),'dd did not delete the line');
 await keypress('u');
 await until(async()=>JSON.parse(await js('window.fieldwork.load()')).active.code.includes('// vim-test'),'Vim undo did not restore the line');
 await keypress('g');await keypress('g');
 await keypress('o');
 await until(async()=>(await text()).includes('--INSERT--'),'o did not enter Insert mode');
 await win.webContents.insertText('// opened with o');
 await keypress('Escape');
 await until(async()=>JSON.parse(await js('window.fieldwork.load()')).active.code.includes('// vim-test\n// opened with o\n'),'o did not open a new line below');
 await keypress('v');
 await until(async()=>(await text()).includes('--VISUAL--'),'Vim Visual mode did not activate');
 await keypress('Escape');
 console.log('PASS: Vim Insert/Normal/Visual modes, gg, dd, undo, o newline, and autosave');
 await js(`document.querySelector('#notes').value='Smoke test: maintain an invariant'; document.querySelector('#notes').dispatchEvent(new Event('input',{bubbles:true}));`);
 await click('[data-action="pause"]');
 const before=await js('document.querySelector("#timer").textContent');await sleep(1100);assert.equal(await js('document.querySelector("#timer").textContent'),before);
 await click('[data-action="extend"]');assert.match(await js('document.querySelector("#timer-caption").textContent'),/45-minute/);
 await click('[data-action="check-code"]');
 await until(async()=>(await text()).includes('No syntax errors found'),'Native C++ compiler check did not succeed');
 console.log('PASS: timer pause / extension and native compiler IPC');
 await js('document.querySelector("#code-editor").scrollIntoView({block:"center"})');
 await js('new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)))');
 await writeFile('artifacts/session.png',(await win.webContents.capturePage()).toPNG());
 await click('[data-view="today"]');
 win.webContents.reload();
 await until(async()=>(await text()).includes('Resume session'),'Session did not survive reload');
 await click('[data-action="start"]');
 assert.equal(await js('document.querySelector("#notes").value'),'Smoke test: maintain an invariant');
 console.log('PASS: active session and scratchpad persistence');
 await click('[data-action="help"]');
 await click('[data-action="reflect"]');
 assert.equal(await js('document.querySelector("#outcome").value'),'assisted');
 await click('[data-action="save-result"]');
 await until(async()=>(await text()).includes('Used help'),'Result was not saved');
 await click('[data-view="reviews"]');assert.match(await text(),/Previously used help/);
 await click('[data-view="map"]');assert.match(await text(),/0\/3 \+ review/);
 console.log('PASS: assisted solve, scheduled review, no unearned promotion');
 await click('[data-view="library"]');
 await js(`const s=document.querySelector('#search');s.value='1690D';s.dispatchEvent(new Event('input',{bubbles:true}));`);
 assert.match(await text(),/Black and White Stripe/);
 assert.match(await text(),/1 matching problems/);
 console.log('PASS: catalog search');
 await click('[data-view="settings"]');
 await click('[data-action="sync"]');
 await until(async()=>(await text()).includes('Synced 31 accepted')||(await text()).includes('Synced 32 accepted')||!(await text()).includes('Syncing…'),'Account sync timeout');
 const saved=JSON.parse(await js('window.fieldwork.load()'));
 assert.ok(saved.logs.length===1&&saved.logs[0].outcome==='assisted');
 assert.ok(saved.logs[0].code.includes('int main'));
 assert.ok(Object.keys(saved.profile.accepted).length>0,'Codeforces sync did not return acceptance timestamps');
 console.log('PASS: live Codeforces sync, disk persistence and saved C++ source');
 assert.equal(errors.length,0,errors.join('\n'));
 console.log('Native integration checks passed. Screenshots saved in artifacts/.');
 app.exit(0);
}catch(e){console.error(e);app.exit(1);}

});
