// Native Electron integration checks. Uses an isolated data directory, never the user's progress.
import {app,BrowserWindow,clipboard} from 'electron';
import {mkdtemp,writeFile,readFile,mkdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import assert from 'node:assert/strict';
const testData=await mkdtemp(join(tmpdir(),'fieldwork-desktop-test-'));
app.setPath('userData',testData);
await import('../dist-electron/main.js');
void app.whenReady().then(async()=>{
const originalClipboard=await clipboard.readText();
const sleep=n=>new Promise(r=>setTimeout(r,n));
const until=async(fn,message)=>{for(let i=0;i<160;i++){if(await fn())return;await sleep(100);}throw new Error(message);};
try{
 await until(()=>BrowserWindow.getAllWindows().length>0,'No desktop window');
 const win=BrowserWindow.getAllWindows()[0];
 win.webContents.setBackgroundThrottling(false);
 const js=code=>win.webContents.executeJavaScript(code);
 const text=()=>js('document.body.innerText');
 const click=selector=>js(`document.querySelector(${JSON.stringify(selector)}).click()`);
 const screenshot=async name=>{try{await sleep(200);await writeFile(`artifacts/${name}.png`,(await win.webContents.capturePage()).toPNG());}catch(e){console.warn(`Screenshot ${name} unavailable: ${e.message}`);}};
 const errors=[];win.webContents.on('console-message',details=>{if(details.level==='error')errors.push(details.message);});
 await until(async()=>(await text()).includes('Make room for one good problem.'),'Dashboard did not load');
 assert.match(await text(),/10|Today/);
 await mkdir('artifacts',{recursive:true});
 await sleep(200);
 await screenshot('dashboard');
 console.log('PASS: native dashboard and renderer bridge');
 await click('[data-action="start"]');
 await until(async()=>(await text()).includes('C++ workspace'),'Session did not open');
 await until(()=>js('!!document.querySelector(".monaco-editor")'),'Editor failed to mount');
 await until(async()=>(await text()).includes('--NORMAL--'),'Vim did not initialize in Normal mode');
 await js('document.querySelector(".monaco-editor textarea").focus()');
 const keypress=async key=>{win.webContents.sendInputEvent({type:'keyDown',keyCode:key});win.webContents.sendInputEvent({type:'keyUp',keyCode:key});await sleep(60);};
 await keypress('i');
 await until(async()=>(await text()).includes('--INSERT--'),'Vim did not enter Insert mode');
 await win.webContents.insertText('// vim-test\n');
 await until(async()=>JSON.parse(await js('window.fieldwork.load()')).active.code.includes('// vim-test'),'Insert-mode typing did not reach the model');
 await keypress('Escape');
 await until(async()=>(await text()).includes('--NORMAL--'),'Escape did not return to Normal mode');
 await keypress('g');await keypress('g');await keypress('d');await keypress('d');
 await until(async()=>!JSON.parse(await js('window.fieldwork.load()')).active.code.includes('// vim-test'),'dd did not delete the line');
 await keypress('u');
 await until(async()=>JSON.parse(await js('window.fieldwork.load()')).active.code.includes('// vim-test'),'Vim undo did not restore the line');
 await keypress('g');await keypress('g');
 await keypress('o');
 await until(async()=>(await text()).includes('--INSERT--'),'o did not enter Insert mode');
 await win.webContents.insertText('// opened with o');
 await keypress('Escape');
 await until(async()=>JSON.parse(await js('window.fieldwork.load()')).active.code.includes('// vim-test\n// opened with o\n'),'o did not open a new line below');
 await keypress('v');
 await until(async()=>(await text()).includes('--VISUAL--'),'Vim Visual mode did not activate');
 await keypress('Escape');
 console.log('PASS: Vim Insert/Normal/Visual modes, gg, dd, undo, o newline, and autosave');
 const beforePaste=JSON.parse(await js('window.fieldwork.load()')).active.code;
 const pasted='// clipboard test\n'+beforePaste;
 await clipboard.writeText(pasted);
 await click('[data-action="select-code"]');await click('[data-action="paste-code"]');
 await until(async()=>JSON.parse(await js('window.fieldwork.load()')).active.code===pasted,'Paste button did not replace selected code');
 await click('[data-action="copy-code"]');
 await until(async()=>(await clipboard.readText())===pasted,'Copy button did not copy the whole solution');
 await js('document.querySelector(".monaco-editor textarea").focus()');await keypress('u');
 await until(async()=>JSON.parse(await js('window.fieldwork.load()')).active.code===beforePaste,'Pasting was not undoable');
 const systemKey=async key=>{win.webContents.sendInputEvent({type:'keyDown',keyCode:key,modifiers:[process.platform==='darwin'?'meta':'control']});win.webContents.sendInputEvent({type:'keyUp',keyCode:key,modifiers:[process.platform==='darwin'?'meta':'control']});await sleep(100);};
 await systemKey('a');await systemKey('c');
 await until(async()=>(await clipboard.readText())===beforePaste,'System select-all / copy shortcuts failed in Vim');
 await clipboard.writeText(pasted);await systemKey('v');
 await until(async()=>JSON.parse(await js('window.fieldwork.load()')).active.code===pasted,'System paste shortcut failed in Vim');
 await keypress('u');
 await until(async()=>JSON.parse(await js('window.fieldwork.load()')).active.code===beforePaste,'System paste was not undoable');
 console.log('PASS: copy/paste buttons, system shortcuts in Vim, selection replacement and undo');

 await js(`document.querySelector('#notes').value='Smoke test: maintain an invariant'; document.querySelector('#notes').dispatchEvent(new Event('input',{bubbles:true}));`);
 await click('[data-action="pause"]');
 const before=await js('document.querySelector("#timer").textContent');await sleep(1100);assert.equal(await js('document.querySelector("#timer").textContent'),before);
 await click('[data-action="extend"]');assert.match(await js('document.querySelector("#timer-caption").textContent'),/45-minute/);
 await click('[data-action="check-code"]');
 await until(async()=>(await text()).includes('No syntax errors found'),'Native C++ compiler check did not succeed');
 console.log('PASS: timer pause / extension and native compiler IPC');
 await js('document.querySelector("#code-editor").scrollIntoView({block:"center"})');
 await sleep(200);
 await screenshot('session');
 await click('[data-view="today"]');
 win.webContents.reload();
 await until(async()=>(await text()).includes('Resume session'),'Session did not survive reload');
 await click('[data-action="start"]');
 assert.equal(await js('document.querySelector("#notes").value'),'Smoke test: maintain an invariant');
 console.log('PASS: active session and scratchpad persistence');
 await click('[data-action="help"]');
 await click('[data-action="reflect"]');
 assert.equal(await js('document.querySelector("#outcome").value'),'assisted');
 await js(`document.querySelector('#takeaway').value='Remember the invariant, including <bounds>.';document.querySelector('#takeaway').dispatchEvent(new Event('input'));document.querySelector('#blocker').value='Proving correctness';document.querySelector('#blocker').dispatchEvent(new Event('change'));`);
 await until(async()=>JSON.parse(await js('window.fieldwork.load()')).active.reflectionDraft?.blocker==='Proving correctness','Reflection draft was not saved');
 win.webContents.reload();
 await until(async()=>(await text()).includes('Resume session'),'Draft reload failed');
 await click('[data-action="start"]');await click('[data-action="reflect"]');
 assert.equal(await js('document.querySelector("#takeaway").value'),'Remember the invariant, including <bounds>.');
 assert.equal(await js('document.querySelector("#blocker").value'),'Proving correctness');
 await click('[data-action="save-result"]');
 await until(async()=>(await text()).includes('Used help'),'Result was not saved');
 assert.match(await js('document.querySelector(".continue-card").innerText'),/Continue practice/);
 await js('window.scrollTo(0,0)');
 await sleep(200);
 await screenshot('progress');
 await click('.continue-card [data-action="start"]');
 await until(async()=>(await text()).includes('C++ workspace'),'Continue practice did not open the next problem');
 const continued=JSON.parse(await js('window.fieldwork.load()')).active.problemId;
 await click('[data-view="journal"]');
 assert.match(await js('document.querySelector(".continue-card").innerText'),/Resume session/);
 await click('.continue-card [data-action="start"]');
 await until(async()=>{const a=JSON.parse(await js('window.fieldwork.load()')).active;return a.problemId===continued&&a.runningSince!==null;},'Resume did not preserve the active problem and restart the timer');
 console.log('PASS: Progress continues the next problem and resumes an active session');
 await click('[data-view="reviews"]');assert.match(await text(),/Previously used help/);
 await click('.attempt-history > summary');
 assert.match(await text(),/Remember the invariant, including <bounds>/);
 assert.match(await text(),/Proving correctness/);
 await click('.saved-attempt details summary');assert.match(await text(),/int main/);
 await screenshot('reviews');
 console.log('PASS: reflection draft survives reload and saved reflection/code are accessible in review queue');
 await click('[data-view="map"]');assert.match(await text(),/0\/3 \+ review/);
 console.log('PASS: assisted solve, scheduled review, no unearned promotion');
 await click('[data-view="library"]');
 await js(`const s=document.querySelector('#search');s.value='1690D';s.dispatchEvent(new Event('input',{bubbles:true}));`);
 assert.match(await text(),/Black and White Stripe/);
 assert.match(await text(),/1 matching problems/);
 console.log('PASS: catalog search');
 await click('[data-view="settings"]');
 assert.equal(await js('document.querySelector("#handle").disabled'),false);
 await js('document.querySelector("#handle").value="bad handle";document.querySelector("#handle").dispatchEvent(new Event("input",{bubbles:true}));document.querySelector("#handle").dispatchEvent(new KeyboardEvent("keydown",{key:"Enter",bubbles:true}));');
 assert.match(await text(),/Enter a valid Codeforces handle/);
 await click('[data-action="sync-current"]');
 assert.equal(await js('document.querySelector("[data-action=sync-current]").disabled'),true);
 await until(async()=>!(await js('document.querySelector("[data-action=sync-current]").disabled')),'Sidebar sync timeout');
 assert.equal(await js('document.querySelector("#handle").value'),'bad handle','Sidebar sync discarded the unsaved handle');
 assert.match(await text(),/Synced \d+ accepted/);
 const trackedHandle=JSON.parse(await js('window.fieldwork.load()')).profile.handle;
 await js(`document.querySelector('#handle').value=${JSON.stringify(' marcellus_at_syracuse ')};document.querySelector('#handle').dispatchEvent(new Event('input',{bubbles:true}));document.querySelector('#handle').dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true}));`);
 await until(async()=>(await text()).includes('Synced 31 accepted')||(await text()).includes('Synced 32 accepted')||!(await text()).includes('Syncing…'),'Account sync timeout');
 const saved=JSON.parse(await js('window.fieldwork.load()'));
 assert.ok(saved.logs.length===1&&saved.logs[0].outcome==='assisted');
 assert.ok(saved.logs[0].code.includes('int main'));
 assert.ok(Object.keys(saved.profile.accepted).length>0,'Codeforces sync did not return acceptance timestamps');
 assert.equal(saved.profile.handle,trackedHandle);
 console.log('PASS: editable handle, Enter to sync, validation, disk persistence and saved C++ source');
 await click('[data-view="today"]');await click('[data-action="start"]');
 await click('[data-action="reflect"]');await click('[data-action="save-result"]');
 await click('[data-view="reviews"]');await click(`[data-review="${saved.logs[0].id}"]`);
 await click('[data-saved-review] > summary');
 await until(async()=>JSON.parse(await js('window.fieldwork.load()')).active.help,'Revealing the previous solution did not record help');
 assert.match(await text(),/Remember the invariant, including <bounds>/);
 await click('[data-action="reflect"]');
 assert.equal(await js('document.querySelector("#outcome").value'),'assisted');
 await click('[data-action="save-result"]');await click('[data-view="reviews"]');
 await js('document.querySelectorAll(".attempt-history").forEach(el=>el.open=true)');
 assert.match(await text(),/No reflection was recorded for this attempt/);
 assert.match(await text(),/Remember the invariant, including <bounds>/);
 console.log('PASS: review reveals count as help and older reflections survive blank repeat attempts');
 assert.equal(errors.length,0,errors.join('\n'));
 console.log('Native integration checks passed. Screenshots saved in artifacts/.');
 await clipboard.writeText(originalClipboard);
 app.exit(0);
}catch(e){await clipboard.writeText(originalClipboard);console.error(e);app.exit(1);}

});
