import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {progress,plan,reviews,qualified,elapsed,verifyLogs,validState,DAY,candidates,ratingLadders,trackProfile} from '../src/engine.ts';
import {topics} from '../src/topics.ts';
const seed=JSON.parse(await readFile(new URL('../public/seed.json',import.meta.url)));
const catalog=JSON.parse(await readFile(new URL('../public/catalog.json',import.meta.url))).problems;
const fresh=()=>({version:1,duration:30,initialBand:800,profile:{...structuredClone(seed),accepted:{}},logs:[],active:null,deferred:{}});
const log=(overrides={})=>({id:crypto.randomUUID(),problemId:'100A',topicId:'implementation',rating:800,startedAt:100000,finishedAt:100000+1200000,seconds:1200,outcome:'independent',help:false,verified:true,review:false,notes:'Invariant',blocker:'',checks:[true,true,true],...overrides});
test('historical high-rated accepts do not inflate any category',()=>{const s=fresh();for(const t of topics){assert.equal(progress(s,t.id).band,800);assert.equal(progress(s,t.id).cleared,null);}});
test('promotion requires three distinct verified solves and a delayed repeat',()=>{const s=fresh();s.logs=[log(),log({problemId:'101A'}),log({problemId:'102A'})];assert.equal(progress(s,'implementation').band,800);s.logs.push(log({review:true,startedAt:s.logs[0].finishedAt+2*DAY,finishedAt:s.logs[0].finishedAt+2*DAY+1200000}));assert.equal(progress(s,'implementation').band,900);assert.equal(progress(s,'implementation').cleared,800);assert.equal(progress(s,'graphs').band,800);});
test('repeated fresh IDs cannot substitute for three distinct problems',()=>{const s=fresh();s.logs=[log(),log(),log(),log({review:true,startedAt:4*DAY,finishedAt:4*DAY+1200000})];assert.equal(progress(s,'implementation').band,800);});
test('help, slow solves, incomplete checks, unverified results never qualify',()=>{for(const override of [{help:true},{seconds:1501},{verified:false},{outcome:'assisted'},{outcome:'stuck'},{checks:[true,false,true]}])assert.equal(qualified(log(override)),false);assert.equal(qualified(log({seconds:1500})),true);});
test('review before 48 hours cannot unlock promotion',()=>{const s=fresh();s.logs=[log(),log({problemId:'101A'}),log({problemId:'102A'}),log({review:true,startedAt:DAY,finishedAt:DAY+1200000})];assert.equal(progress(s,'implementation').band,800);});
test('off-band solves never skip rating levels',()=>{const s=fresh();s.logs=[log({rating:1600}),log({problemId:'101A',rating:1600}),log({problemId:'102A',rating:1600}),log({rating:1600,review:true,startedAt:4*DAY,finishedAt:4*DAY+1200000})];assert.equal(progress(s,'implementation').band,800);});
test('assisted learning can later earn credit through independent delayed recall',()=>{const s=fresh();s.logs=[log({outcome:'assisted',help:true}),log({review:true,startedAt:4*DAY,finishedAt:4*DAY+1200000})];assert.equal(progress(s,'implementation').fresh,1);assert.equal(progress(s,'implementation').reviewed,false);s.logs.push(log({review:true,startedAt:8*DAY,finishedAt:8*DAY+1200000}));assert.equal(progress(s,'implementation').fresh,1);assert.equal(progress(s,'implementation').reviewed,true);});
test('planner uses exact bands, excludes historical accepts, rotates categories',()=>{const s=fresh();const first=plan(s,catalog);assert.equal(first.problem.rating,800);assert.ok(!s.profile.solved.some(p=>`${p.contestId}${p.index}`===first.problem.id));s.logs.push(log({problemId:first.problem.id,topicId:first.topic.id,finishedAt:Date.now()}));const second=plan(s,catalog);assert.notEqual(second.topic.id,first.topic.id);assert.equal(second.problem.rating,800);});
test('due reviews do not starve fresh categories',()=>{const s=fresh();const p=plan(s,catalog);s.logs=[log({problemId:p.problem.id,topicId:p.topic.id})];const due=plan(s,catalog,10*DAY);assert.equal(due.review,true);s.logs.push(log({problemId:p.problem.id,review:true,finishedAt:10*DAY,startedAt:10*DAY-1200000}));assert.equal(plan(s,catalog,10*DAY+1000).review,false);});
test('review spacing expands after qualifying retrieval',()=>{const s=fresh();s.logs=[log()];assert.equal(reviews(s)[0].dueAt,s.logs[0].finishedAt+2*DAY);s.logs.push(log({review:true,startedAt:4*DAY,finishedAt:4*DAY+1200000}));assert.equal(reviews(s)[0].dueAt,s.logs[1].finishedAt+7*DAY);});
test('acceptance must occur after session start, including reviews',()=>{const s=fresh();s.logs=[log({verified:false}),log({problemId:'101A',review:true,verified:false})];s.profile.accepted={'100A':99999,'101A':200000};verifyLogs(s);assert.equal(s.logs[0].verified,false);assert.equal(s.logs[1].verified,true);});
test('timer uses wall-clock deltas and pauses exactly',()=>{assert.equal(elapsed({elapsed:10,runningSince:1000},6000),15);assert.equal(elapsed({elapsed:10,runningSince:null},999999),10);});
test('backup validation rejects corrupt progress',()=>{const s=fresh();assert.equal(validState(s),true);assert.equal(validState({...s,logs:[{id:'bad'}]}),false);assert.equal(validState({...s,initialBand:5000}),false);assert.equal(validState({...s,active:{problemId:'x'}}),false);});
test('sparse bands use the next supported rating without inventing earned credit',()=>{const s=fresh();s.bands=ratingLadders(catalog);assert.equal(progress(s,'dsu').band,1100);assert.equal(progress(s,'dsu').cleared,null);for(const t of topics){const band=progress(s,t.id).band;const n=catalog.filter(p=>p.rating===band&&p.tags.some(tag=>t.tags.includes(tag))).length;assert.ok(n>=3,`${t.name} only has ${n} problems at ${band}`);}});

test('switching handles isolates verification and restores prior practice',()=>{
 const s=fresh();const original=structuredClone(s.profile);s.logs=[log({verified:false})];
 s.active={problemId:'100B',topicId:'implementation',rating:800,startedAt:1000,elapsed:5,runningSince:1000,duration:30,review:false,help:false,notes:'keep me',checks:[false,false,false],code:'int main(){}'};
 trackProfile(s,{...original,handle:'another_user',accepted:{'100A':300000}},6000);
 assert.equal(s.logs.length,0);assert.equal(s.active,null);assert.equal(s.accounts[original.handle].logs[0].verified,false);
 s.logs=[log({problemId:'200A'})];trackProfile(s,original,7000);
 assert.equal(s.logs[0].problemId,'100A');assert.equal(s.logs[0].verified,false);assert.equal(s.active.notes,'keep me');assert.equal(s.active.elapsed,10);assert.equal(s.active.runningSince,null);
 assert.equal(s.accounts.another_user.logs[0].problemId,'200A');assert.equal(validState(s),true);
});
test('case-only handle updates do not reset progress',()=>{const s=fresh();s.logs=[log()];trackProfile(s,{...s.profile,handle:s.profile.handle.toUpperCase()});assert.equal(s.logs.length,1);assert.equal(s.accounts,undefined);});
test('corrupt account archives are rejected on import',()=>{const s=fresh();assert.equal(validState({...s,accounts:{broken:{logs:[{bad:true}]}}}),false);});
