export interface ConceptLadder {
 id:string;
 title:string;
 topicId:string;
 description:string;
 steps:{id:string;title:string;concept:string;buildsOn:string;codeforcesIds:string[];leetcode:{slug:string;title:string;difficulty:'Easy'|'Medium'|'Hard'}[]}[];
}

// LeetCode titles and difficulties checked against the linked official problem
// pages. CF exercises are transfer practice, not difficulty-equivalent duplicates.
export const ladders:ConceptLadder[]=[
 {id:'lookup-patterns',title:'From lookups to prefix counts',topicId:'structures',description:'Remember what you have seen, then turn pair and range questions into lookups.',steps:[
  {id:'lookup-seen',title:'Remember seen values',concept:'Use a set for membership and a map when a value needs a count. Recall: explain when to check before inserting.',buildsOn:'Prerequisite: loops, arrays, and equality comparisons.',codeforcesIds:['4C'],leetcode:[{slug:'contains-duplicate',title:'Contains Duplicate',difficulty:'Easy'}]},
  {id:'lookup-complement',title:'Look up a complement',concept:'Replace a scan of earlier elements with a lookup for target minus the current value. Recall: trace two equal values without reusing an index.',buildsOn:'Builds on seen values: the lookup key can be a derived value, not just the current element.',codeforcesIds:[],leetcode:[{slug:'two-sum',title:'Two Sum',difficulty:'Easy'}]},
  {id:'lookup-prefix',title:'Count prefix complements',concept:'Express a subarray sum as the difference of two prefix sums, and count earlier matching prefixes. Recall: justify the initial zero-prefix entry.',buildsOn:'Builds on complement lookup: store frequencies instead of one index. CF Good Subarrays adds a prefix transformation.',codeforcesIds:['1398C'],leetcode:[{slug:'subarray-sum-equals-k',title:'Subarray Sum Equals K',difficulty:'Medium'}]}
 ]},
 {id:'window-patterns',title:'From fixed windows to valid ranges',topicId:'windows',description:'Reuse work while boundaries move, then learn exactly when the left boundary must advance.',steps:[
  {id:'window-fixed',title:'Slide a fixed-length window',concept:'Remove the outgoing value and add the incoming value. Recall: write the window boundaries and initialization without code.',buildsOn:'Prerequisite: array indices, running sums, and contiguous subarrays.',codeforcesIds:['363B'],leetcode:[{slug:'maximum-average-subarray-i',title:'Maximum Average Subarray I',difficulty:'Easy'}]},
  {id:'window-variable',title:'Move both boundaries',concept:'Expand and shrink a positive-sum window under a target or budget. Recall: explain why negative values would break this reasoning.',buildsOn:'Builds on fixed windows: the maintained sum stays the same idea, but the width becomes a decision.',codeforcesIds:['279B'],leetcode:[{slug:'minimum-size-subarray-sum',title:'Minimum Size Subarray Sum',difficulty:'Medium'}]},
  {id:'window-frequency',title:'Maintain a frequency invariant',concept:'Track characters in the current window and repair duplicate violations. Recall: trace abba and explain why the left boundary never moves backward.',buildsOn:'Builds on variable windows: replace the sum condition with a frequency condition. Requires basic set or map operations.',codeforcesIds:[],leetcode:[{slug:'longest-substring-without-repeating-characters',title:'Longest Substring Without Repeating Characters',difficulty:'Medium'}]}
 ]},
 {id:'boundary-patterns',title:'From sorted lookup to answer search',topicId:'search',description:'Keep a search invariant, locate exact boundaries, then search a space of possible answers.',steps:[
  {id:'boundary-lookup',title:'Keep a binary-search invariant',concept:'Discard a half only when the target cannot be there. Recall: trace an absent target and a one-element array.',buildsOn:'Prerequisite: sorted arrays, integer indices, and comparisons.',codeforcesIds:[],leetcode:[{slug:'binary-search',title:'Binary Search',difficulty:'Easy'}]},
  {id:'boundary-first',title:'Find the first or last valid index',concept:'Find a boundary even when matching values repeat; use lower and upper bounds deliberately. Recall: state what remains true on each side.',buildsOn:'Builds on binary lookup: finding any match becomes finding the transition. CF Worms also needs prefix sums.',codeforcesIds:['706B','474B'],leetcode:[{slug:'find-first-and-last-position-of-element-in-sorted-array',title:'Find First and Last Position of Element in Sorted Array',difficulty:'Medium'}]},
  {id:'boundary-answer',title:'Search the answer itself',concept:'Write a feasibility check and prove that it changes direction only once. Recall: derive safe bounds and test integer rounding.',buildsOn:'Builds on boundary search: the sorted object is now a sequence of true/false feasibility results.',codeforcesIds:['371C'],leetcode:[{slug:'koko-eating-bananas',title:'Koko Eating Bananas',difficulty:'Medium'}]}
 ]},
 {id:'stack-patterns',title:'From pending work to monotonic stacks',topicId:'structures',description:'Use the stack top to represent unfinished work, then preserve useful summaries and order.',steps:[
  {id:'stack-match',title:'Match the latest opening',concept:'Keep unmatched openings and require each closing bracket to match the top. Recall: explain why a queue cannot replace the stack.',buildsOn:'Prerequisite: sequential scans and push/pop operations. CF uses a single bracket type and asks for the longest valid subsequence.',codeforcesIds:['26B'],leetcode:[{slug:'valid-parentheses',title:'Valid Parentheses',difficulty:'Easy'}]},
  {id:'stack-summary',title:'Attach a summary to each depth',concept:'Store enough information to recover the minimum after a pop. Recall: trace repeated minima and explain why one global minimum is insufficient.',buildsOn:'Builds on stack state: each push preserves a summary of everything below it.',codeforcesIds:[],leetcode:[{slug:'min-stack',title:'Min Stack',difficulty:'Medium'}]},
  {id:'stack-monotonic',title:'Resolve pending indices in order',concept:'Keep unresolved indices in temperature order and resolve them when a warmer value arrives. Recall: prove each index is pushed and popped at most once.',buildsOn:'Builds on stack summaries: the stack itself now maintains an ordering invariant.',codeforcesIds:[],leetcode:[{slug:'daily-temperatures',title:'Daily Temperatures',difficulty:'Medium'}]}
 ]},
 {id:'traversal-patterns',title:'From reachability to BFS layers',topicId:'graphs',description:'Explore one component, count all components, then attach distance to the exploration.',steps:[
  {id:'traversal-reachable',title:'Visit a connected region',concept:'Traverse valid neighbors and mark each cell before revisiting it. Recall: explain the unchanged-color case and recursion-depth risk.',buildsOn:'Prerequisite: grid bounds and a stack or queue.',codeforcesIds:[],leetcode:[{slug:'flood-fill',title:'Flood Fill',difficulty:'Easy'}]},
  {id:'traversal-components',title:'Count disconnected components',concept:'Restart traversal at every unvisited valid vertex. Recall: explain why each restart counts exactly one component.',buildsOn:'Builds on one-region traversal: add an outer scan. CF Ice Skating changes which pairs of points are neighbors.',codeforcesIds:['217A'],leetcode:[{slug:'number-of-islands',title:'Number of Islands',difficulty:'Medium'}]},
  {id:'traversal-distance',title:'Explore simultaneous BFS layers',concept:'Use a queue to process distance layers; initialize all sources for simultaneous spread. Recall: explain why DFS visitation order does not give shortest distances.',buildsOn:'Builds on visited-state traversal: add arrival time. CF Two Buttons transfers the queue idea to an implicit graph with one source.',codeforcesIds:['520B'],leetcode:[{slug:'rotting-oranges',title:'Rotting Oranges',difficulty:'Medium'}]}
 ]},
 {id:'dp-patterns',title:'From recurrence to optimization',topicId:'dp',description:'Define what one state means, then vary the choices and the quantity you combine.',steps:[
  {id:'dp-count',title:'Count ways to reach a state',concept:'Partition solutions by their last move and combine smaller states. Recall: derive the recurrence and base cases before coding.',buildsOn:'Prerequisite: arrays, loops, and basic recursion.',codeforcesIds:[],leetcode:[{slug:'climbing-stairs',title:'Climbing Stairs',difficulty:'Easy'}]},
  {id:'dp-choice',title:'Choose or skip with a constraint',concept:'Compare taking the current reward with skipping it. Recall: state which earlier choice is excluded when you take it.',buildsOn:'Builds on recurrence states: replace counting with maximization. CF Boredom first aggregates rewards by value.',codeforcesIds:['455A'],leetcode:[{slug:'house-robber',title:'House Robber',difficulty:'Medium'}]},
  {id:'dp-unbounded',title:'Optimize over reusable choices',concept:'Try every permitted last choice and represent unreachable states explicitly. Recall: explain why the evaluation order makes dependencies available.',buildsOn:'Builds on optimizing a state: expand two choices to many reusable sizes. CF Cut Ribbon maximizes pieces while Coin Change minimizes them.',codeforcesIds:['189A'],leetcode:[{slug:'coin-change',title:'Coin Change',difficulty:'Medium'}]}
 ]},
 {id:'tree-patterns',title:'From subtree height to path summaries',topicId:'trees',description:'Return information from children and separate what a parent can extend from the best complete path.',steps:[
  {id:'tree-height',title:'Return a subtree height',concept:'Combine child heights with a precise empty-subtree base case. Recall: distinguish node depth from edge distance.',buildsOn:'Prerequisite: recursion and a rooted tree. CF Party transfers depth reasoning to a forest of manager chains.',codeforcesIds:['115A'],leetcode:[{slug:'maximum-depth-of-binary-tree',title:'Maximum Depth of Binary Tree',difficulty:'Easy'}]},
  {id:'tree-diameter',title:'Combine two child summaries',concept:'Return one downward height while checking a path through both children. Recall: explain why the longest path need not pass through the root.',buildsOn:'Builds on subtree height: distinguish the value returned to the parent from the best answer seen anywhere.',codeforcesIds:[],leetcode:[{slug:'diameter-of-binary-tree',title:'Diameter of Binary Tree',difficulty:'Easy'}]},
  {id:'tree-weighted',title:'Extend only a profitable branch',concept:'Replace path length with node weights, allowing unhelpful branches to be omitted. Recall: handle an all-negative tree without choosing an empty path.',buildsOn:'Builds on diameter: keep the return-versus-global-answer distinction while introducing negative contributions.',codeforcesIds:[],leetcode:[{slug:'binary-tree-maximum-path-sum',title:'Binary Tree Maximum Path Sum',difficulty:'Hard'}]}
 ]},
 {id:'greedy-patterns',title:'From exchange arguments to intervals',topicId:'greedy',description:'Make a local choice, justify replacing an optimal choice with it, then carry that proof to intervals.',steps:[
  {id:'greedy-exchange',title:'Preserve future options',concept:'Sort candidates and justify a local choice by swapping it into an optimal solution. Recall: explain which future choices your decision preserves.',buildsOn:'Prerequisite: sorting and comparisons. CF Twins uses largest-first selection; Assign Cookies uses the smallest sufficient match.',codeforcesIds:['160A'],leetcode:[{slug:'assign-cookies',title:'Assign Cookies',difficulty:'Easy'}]},
  {id:'greedy-schedule',title:'Keep intervals that finish early',concept:'Choose compatible intervals using the earliest finishing time. Recall: produce a counterexample to choosing the earliest starting interval.',buildsOn:'Builds on exchange arguments: replacing a choice must leave at least as much room for future intervals.',codeforcesIds:[],leetcode:[{slug:'non-overlapping-intervals',title:'Non-overlapping Intervals',difficulty:'Medium'}]},
  {id:'greedy-cover',title:'Cover intervals at a shared endpoint',concept:'Place a point at the earliest end and reuse it for every interval it hits. Recall: compare touching endpoints with the previous problem.',buildsOn:'Builds on sorting by end: change the objective from selecting disjoint intervals to covering overlapping intervals.',codeforcesIds:[],leetcode:[{slug:'minimum-number-of-arrows-to-burst-balloons',title:'Minimum Number of Arrows to Burst Balloons',difficulty:'Medium'}]}
 ]}
];

/** Earliest step with unfinished exercises; provider-prefixed keys avoid collisions. */
export function nextLadderStep(ladder:ConceptLadder,completed:ReadonlySet<string>):ConceptLadder['steps'][number]|undefined {
 return ladder.steps.find(step=>step.codeforcesIds.some(id=>!completed.has(`cf:${id}`))||step.leetcode.some(problem=>!completed.has(`lc:${problem.slug}`)));
}
